# Lineare Gleichungssysteme

In [2]:
import numpy as np

### LR-Zerlegung

In [10]:
def LUdecomp(A):
    '''returns upper and lower triangular matrices L, U which satisfy LU=A'''
    
    A = np.array(A)
    n = len(A)
    R = A
    L = np.eye(n)
    
    for k in range(n):
        for j in range(k+1, n):
            L[j, k] = R[j, k] / R[k, k]
            R[j, k:] = R[j, k:] - L[j, k] * R[k, k:]
    
    return L, R

In [4]:
def GaussSolve(A, b):
    '''returns solution x of Ax=b'''
    
    A = np.array(A)
    b = np.array(b)
    n = len(b)
    if A.shape != (n, n):
        raise Exception("shape mismatch")
    
    M = np.zeros((n, n))
    c = np.zeros(n)
    
    # solve Ly = b
    for k in range(n):
        c[k] = 0
        M[k:, k] = np.zeros(n-k)
        
        c[k+1:] = A[k+1:, k] / A[k, k]
        M[:, k] = c
        L = np.eye(n) - M
        A = L @ A
        b = L @ b
        
    # solve Ux = y
    for k in range(n-1, -1, -1):
        b[k] = (b[k] - sum(A[k, k+1:] * b[k+1:])) / A[k, k]
    
    return b

### LR-Zerlegung mit Pivotierung

In [18]:
def LUdecomp(A):
    A = np.array(A)
    n = len(A)
    U = A
    L = np.eye(n)
    P = np.eye(n)
    
    for k in range(n-1):
        i = np.argmax(abs(U[k:, k])) + k
        U[k, k:], U[i, k:] = U[i, k:], U[k, k:].copy()
        L[k, :k-1], L[i, :k-1] = L[i, :k-1], L[k, :k-1].copy()
        P[k], P[i] = P[i], P[k].copy()
        
        for j in range(k+1, n):
            L[j, k] = U[j, k] / U[k, k]
            U[j, k:] = U[j, k:] - L[j, k] * U[k, k:]
    
    return L, U, P

In [19]:
LUdecomp(np.array([[1,-2,3],[4,5,6],[7,8,-9]]))

(array([[ 0.        ,  0.        ,  0.        ],
        [ 0.57142857,  1.        ,  0.        ],
        [ 0.14285714, -0.        ,  1.        ]]),
 array([[ 7,  8, -9],
        [ 0, -3,  4],
        [ 0,  0, 11]]),
 array([[0., 0., 1.],
        [1., 0., 0.],
        [0., 1., 0.]]))